name: Homebridge
version: 0.2.1
stage: experimental
slug: homebridge
description: Lightweight HomeKit API implementation with plugin support
url: https://github.com/isteve-o/hassio-addons/tree/main/homebridge
arch:
  - armv7
  - aarch64
  - amd64
ingress: true
ingress_port: 8581
host_network: true
init: false
map:
  - addon_config:rw
image: isteveo/{arch}-addon-homebridge
